### ISSUE TITLE
Build Dockerfile from Container Service  REST endpoint

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#2]
_As a funcX function author I want the container service to build a Dockerfile based on simple specifications_

## Assumptions
1. Will support the following repo2docker specifications
* environment.yaml
* Pipfile
* requirements.txt
* setup.py
* apt.txt
* postBuild
2. Creates Dockerfile only (doesn't build the image)
3. Dockerfile is returned in the response.
4. Only repo2docker errors are  trapped and reported.

## Acceptance Criteria
1. Given I have a POST message with a requirements.txt body When I submit it to the endpoint then I should see a correct Dockerfile in the response.
2. When I `docker build` this Dockerfile I get a valid image
3. Given I submit an invalid request, then I should receive a useful error message

**Comment by tshaffe1** [comment]
Highlights from discussion on Slack:

### Input Format
- requirements file(s)
- spec document
- tarball

The requirements files would simply be the package requirements accepted by the various package managers (`requirements.txt` for pip, `environment.yaml` for conda, etc.). Since there may be several such files for a given environment, the endpoint would need to accept multiple inputs, e.g. via multipart/form-data. Not sure if users want to figure out the curl commands to do this...

A spec file would give the requirements and any additional build steps in a single document (probably JSON). This would be a new format that needs to be documented for users, but is very compact and easy to store. It's also the easiest for us to process/transform. Might look something like

    {
        "conda": ["ndcctools"],
        "pip": ["parsl==1.0.0"],
        "apt": ["perl"]
    }

For users that don't already use repo2docker and have requirements files ready, this would be easiest. This method would not allow any additional artifacts to be included (necessary for DLHub use).

We could also have users tar up a repo2docker directory. This gives users the most flexibility (can use include non-Python requirements, can bundle additional artifacts, can customize the dockerfile). More trouble to store (probably keep the tarball in S3). Not safe to modify/transform in the general case since users can include arbitrary code and data.

### Output formats
If we use repo2docker under the hood, it's not possible to return a dockerfile; repo2docker can only build Docker containers. The Docker builds aren't terribly complex, and it would be feasible to do a "repo2docker-like" system that does return a dockerfile. However, this approach would not allow embedding additional artifacts (plain text up to a couple of KB could probably be included inline, but this would be ugly). This approach would only be feasible if a spec document is the only input.

The output could also be a finished Docker container. This is what repo2docker does. Once built, the container can be pushed to ECR or used locally.

### Reproducibility
The finished containers provide the best reproducibility of the technologies under consideration. However, full containers require substantial storage space and might be cleaned up/deleted. Retaining the specification data would allow containers to be rebuilt as needed. A dockerfile would be almost as good as the actual container, though note that changes to the base image or package repos could still result in variation or breakage in the future. Since creating dockerfiles is more trouble/less flexible, we don't consider this option.

Storing the initial user request would also provide reasonable reproducibility. As with storing dockerfiles, the resulting container will not be bit-for-bit identical to a previous build, nor are they guaranteed to be functionally identical. Again, changes in the base image or changes in the Python repos could result in different builds/versions of software being included. In addition, changes to repo2docker itself can affect reproducibility. The particulars of the build steps may vary in future versions of repo2docker, and different versions of the package managers themselves provided by repo2docker may result in different results (e.g. pip or conda modify their solvers in future versions, resulting in different package selections).

Since bit-for-bit reproducibility is not possible (and likely not needed), storing the input spec/tarball should be sufficient.

### Proposed API
To support both the basic Python-only use case as well as more complicated builds (e.g. for DLHub), the container service can provide two different build endpoints:
- Basic endpoint accepts POST requests with the body as a JSON spec like above.
- Advanced endpoint accepts POST requests sending a repo2docker tarball as the body.

In both cases, the response is either an error or on success the ID of the resulting container (UUID?). Note that container builds might take a significant amount of time, so any errors returned immediately would be due to invalid requests (bad spec, couldn't untar, etc.). Thus an additional endpoint is needed:
- Status is a GET request that takes a container ID and returns the status of the container (e.g. building, ready, error, etc.)
- (Is wait/long polling needed?)

**Comment by BenGalewsky** [comment]
From the old project plan - closing as obsolete
