### ISSUE TITLE
Restore CI Workflow

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#9]
#Problem
The current `main` branch is no longer building

# Approach
It looks like a library is failing safety check. Fix this and insure that docker image is published

**Comment by blue442** [comment]
Previous CI workflow in github actions was interrupted by a vulnerability identified by [safety](https://pypi.org/project/safety/) - I couldn't remember which library had an issue, and [the logs appear to be gone](https://github.com/funcx-faas/funcx-container-service/runs/2986723814?check_suite_focus=true), but re-pushing the identical code to 'fix-CI' branch passed with no issues.

This suggests that the vulnerability was likely fixed in the latest version of the package, but raises the question about whether we want to pin package versions in the requirements.txt. My gut says 'eventually', but happy to defer if there are existing best practices, preferences, or tendencies in the group.

**Comment by BenGalewsky** [comment]
@blue442 - take a look at `requirements.txt` - it seems like someone just did a `pip freeze` instead of just putting the top-level dependencies in it.

Also, there are a load of intermediate build warnings around orjson - It seems like it is related to [basing the Docker image on alpine](https://github.com/ijl/orjson/issues/98#issuecomment-642833810)
